// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Principados.Infrastructure.Data;

#nullable disable

namespace Principados.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Principados.Domain.Entities.Character", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("AngelType").IsRequired().HasMaxLength(10).HasColumnType("character varying(10)");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("Name").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
                    b.Property<Guid>("UserId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("Name").IsUnique();
                    b.HasIndex("UserId");
                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Principados.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("Email").IsRequired().HasMaxLength(256).HasColumnType("character varying(256)");
                    b.Property<string>("PasswordHash").IsRequired().HasColumnType("text");
                    b.HasKey("Id");
                    b.HasIndex("Email").IsUnique();
                    b.ToTable("Users");
                });

            modelBuilder.Entity("Principados.Domain.Entities.Character", b =>
                {
                    b.HasOne("Principados.Domain.Entities.User", "User")
                        .WithMany("Characters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("User");
                });

            modelBuilder.Entity("Principados.Domain.Entities.User", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
